### ISSUE TITLE
Privilege Level Abstraction

### ISSUE THREAD

**Issue by unknownerror0** [u7karsh/os_virtual_mem#4]
Even if Xinu does not have a clear difference between user mode and system mode, you should aim at a
design that conceptually distinguished “user mode” and “kernel mode”. To this end, assume that, when a user
process issues a system call, that call is executed in kernel mode. On the other hand, the rest of the user
process’s code (that is, the code within the function executed by the process) is executed in user mode.

Note: We already are doing this, but there is one more separate points of interest:
1. Should the PD/PT address space be allowed to be mapped in virtual address space? I think, yes this is harmless. This virtual space can point to anything. That being said if we keep this virtual space free that's perfectly fine.

**Comment by u7karsh** [comment]
We do not map the PD/PT address space in mapped virtual address space as that could be a potential security issue. PD/PT contains mappings for all programs (it would have been fine if it were just the current process)
